request: 
  method: GET
  path: /agenda/show.json
  queryStringParameters: 		
    user_id:
      - 123
response:
  statusCode: 200
  headers:
    Content-Type: 
      - "application/json"
  body: >
    [
      {  
        "id":"{{request.query.user_id}}",
        "full_name":"{{fake.FirstName}} {{fake.LastName}}",
        "first_name":"{{fake.FirstName}}",
        "last_name":"{{fake.LastName}}",
        "gender":"{{fake.Gender}}",
        "email":"{{fake.EmailAddress}}"
      }
    ]